#ifndef FORGE_CONFIG_H
#define FORGE_CONFIG_H

#ifndef FR_CONFIG_KERNEL_INTERRUPT_CEILING
#define FR_CONFIG_KERNEL_INTERRUPT_CEILING 8u
#endif

#ifndef FR_CONFIG_MAX_TASKS
#define FR_CONFIG_MAX_TASKS 8u
#endif

#ifndef FR_CONFIG_MAX_TASK_PRIORITY
#define FR_CONFIG_MAX_TASK_PRIORITY 31u
#endif

#ifndef FR_CONFIG_MIN_TASK_STACK_WORDS
#define FR_CONFIG_MIN_TASK_STACK_WORDS 32u
#endif

#endif